post_index:
    path:     /
    defaults: { _controller: ApplicationArferrBlogBundle:Posts:index }

post_view:
    path: /posts/{id}
    defaults: { _controller: ApplicationArferrBlogBundle:Posts:view }

comment_add:
    path: /posts/{postId}/comment/create
    defaults: { _controller: ApplicationArferrBlogBundle:Comments:ajaxAdd }

