services:
    application_arferr_blog.admin.post:
        class: Application\Arferr\BlogBundle\Admin\PostAdmin
        arguments: [~, Application\Arferr\BlogBundle\Entity\Post, SonataAdminBundle:CRUD]
        calls:
            - [ setEventDispatcher, [@event_dispatcher]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Blog, label: Post}

    application_arferr_blog.event.new_comment:
        class: Application\Arferr\BlogBundle\Event\NewCommentEvent

    application_arferr_blog.eventListener.new_comment_crm_notifier:
        class: Application\Arferr\BlogBundle\EventListener\CrmNotifier
        arguments: ['http://crm.example.com', 'notification/new-comment-receive']
        tags:
            - {name: kernel.event_listener, event: application_arferr_blog.event.new_comment, method: onNewComment}

    application_arferr_blog.eventListener.new_comment_stats_notifier:
        class: Application\Arferr\BlogBundle\EventListener\StatsNotifier
        arguments: ['http://stats.example.com', 'comments/new']
        tags:
            - {name: kernel.event_listener, event: application_arferr_blog.event.new_comment, method: onNewComment}

    application_arferr_blog.event.new_post:
            class: Application\Arferr\BlogBundle\Event\NewPostEvent

    application_arferr_blog.eventListener.new_post_crm_notifier:
        class: Application\Arferr\BlogBundle\EventListener\CrmNotifier
        arguments: ['http://crm.example.com', 'notification/new-post-receive']
        tags:
            - {name: kernel.event_listener, event: application_arferr_blog.event.new_post, method: onNewPost}

    application_arferr_blog.eventListener.new_post_stats_notifier:
        class: Application\Arferr\BlogBundle\EventListener\StatsNotifier
        arguments: ['http://stats.example.com', 'posts/new']
        tags:
            - {name: kernel.event_listener, event: application_arferr_blog.event.new_post, method: onNewPost}