<?php

namespace Application\Arferr\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllWithAuthors() {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('p, a')
            ->from('\Application\Arferr\BlogBundle\Entity\Post', 'p')
            ->innerJoin('p.author', 'a')
            ->orderBy('p.createdAt', 'desc')
            ->getQuery();

        return $qb->getResult();
    }

    /**
     * @return mixed
     */
    public function findOneByIdWithComments() {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('p, c, a')
            ->from('\Application\Arferr\BlogBundle\Entity\Post', 'p')
            ->leftJoin('p.comments', 'c')
            ->leftJoin('c.author', 'a')
            ->orderBy('c.createdAt', 'desc')
            ->getQuery();

        return $qb->getOneOrNullResult();
    }
}
