Application\Arferr\BlogBundle\Entity\Post:
    type: entity
    table: posts
    repositoryClass: Application\Arferr\BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            options:
                unsigned: true

    fields:
        title:
            type: string
            length: 100
            nullable: false
        content:
            column: content
            type: text
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at

    lifecycleCallbacks:
              prePersist:   [ prePersist ]

    manyToOne:
        author:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: ['persist']
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: SET NULL

    oneToMany:
        comments:
            targetEntity: Application\Arferr\BlogBundle\Entity\Comment
            mappedBy: post
            cascade: ["persist"]